# Generated by Django 4.0.1 on 2022-05-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='')),
                ('small_price', models.IntegerField()),
                ('large_price', models.IntegerField()),
                ('cafe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
        ),
    ]
