# Generated by Django 4.0.1 on 2022-05-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
