# Generated by Django 4.0.1 on 2022-05-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='u_id',
            field=models.IntegerField(),
        ),
    ]
