# Generated by Django 4.0.1 on 2022-05-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='phone',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
