# Generated by Django 4.0.1 on 2022-05-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
