# Generated by Django 4.0.1 on 2022-05-30 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_alter_order_u_id_alter_orderitem_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='u_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
