# Generated by Django 4.0.1 on 2022-05-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_u_id_alter_order_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='u_id',
            new_name='user',
        ),
    ]
