# Generated by Django 4.0.1 on 2022-05-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
